name: Deploy to Firebase Hosting with Astro build

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'  # Asegúrate de usar una versión compatible con Astro
        
      - name: Install dependencies
        run: npm install

      - name: Build Astro project
        run: npm run build  # Ajusta según el comando específico para construir tu proyecto de Astro

      - name: Check if there are changes in dist folder
        id: check_changes
        run: |
          if git diff --quiet; then
            echo "No changes in dist folder."
            echo "::set-output name=changes::false"
          else
            echo "Changes detected in dist folder."
            echo "::set-output name=changes::true"
          fi

      - name: Commit and push changes if any
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add dist
          git commit -m 'Build: Update dist folder'
          git push origin master

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master

      - name: checkout
        uses: actions/checkout@v4
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_ANTONIO_MAZUELOS }}
          channelId: live
          projectId: portfolio-antonio-mazuelos